import hashlib
import os
from pathlib import Path
import re
import subprocess
import sys
import unittest


ROOT = Path(__file__).resolve().parents[1]
PROJECTION = ROOT / "api" / "feed-ranking-v1.yaml"
SYNC = ROOT / "scripts" / "recommendation" / "sync-feed-contract.py"
PROJECTION_DIGEST = "c075235c1f43825abe0e1b8be53a41a8f78aac6f0919b2f3f8e1db41bcd6b467"
CANONICAL_DIGEST = "c028a6dd7ae5e22e941b250e2a81b232d28a8f4ad597fa53aeba2e3b88094710"
EXTENSION_DIGEST = "9c0d46b9f3de8537d0146fe73bf5b77ad8211490d1e9d7473449ea1bb9898683"

REQUIRED_CONDITIONALS = {
    "FeedMonthMetrics": (
        "coverage: {const: COMPLETE}",
        "values: {$ref: '#/components/schemas/FeedCoreMetrics'}",
        "values: {type: \"null\"}",
    ),
    "FeedRankingCandidate": (
        "state: {const: COMPLETED}",
        "closed_at: {type: string, format: date-time}",
        "closed_at: {type: \"null\"}",
    ),
    "FeedRankingError": (
        "code: {const: RANKING_UNAVAILABLE}",
        "retryable: {const: true}",
        "retryable: {const: false}",
    ),
}


def schema_block(document: str, name: str) -> str:
    lines = document.splitlines(keepends=True)
    marker = f"    {name}:\n"
    start = lines.index(marker)
    end = len(lines)
    for index in range(start + 1, len(lines)):
        if re.fullmatch(r"    [A-Za-z][A-Za-z0-9_]*:\n", lines[index]):
            end = index
            break
    return "".join(lines[start:end])


class FeedContractProjectionTest(unittest.TestCase):
    def test_committed_projection_preserves_canonical_metadata_and_conditionals(self):
        projection_bytes = PROJECTION.read_bytes()
        self.assertEqual(hashlib.sha256(projection_bytes).hexdigest(), PROJECTION_DIGEST)
        projection = projection_bytes.decode("utf-8")
        self.assertTrue(
            projection.startswith(
                "# Generated by scripts/recommendation/sync-feed-contract.py; do not hand-edit.\n"
            )
        )
        self.assertEqual(projection.count(f"raw-byte-sha256: sha256:{CANONICAL_DIGEST}"), 1)
        self.assertEqual(projection.count(f"extension-raw-sha256: sha256:{EXTENSION_DIGEST}"), 1)
        for schema, fragments in REQUIRED_CONDITIONALS.items():
            with self.subTest(schema=schema):
                block = schema_block(projection, schema)
                for fragment in fragments:
                    self.assertIn(fragment, block)

    def test_projection_matches_explicit_canonical_backend_contract(self):
        canonical_value = os.environ.get("CRABIT_BACKEND_OPENAPI")
        if canonical_value is None:
            self.skipTest("CRABIT_BACKEND_OPENAPI was not explicitly supplied")
        canonical = Path(canonical_value)
        self.assertTrue(canonical.is_file(), f"explicit canonical OpenAPI is required: {canonical}")
        result = subprocess.run(
            [sys.executable, str(SYNC), str(canonical), "--output", str(PROJECTION), "--check"],
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)


if __name__ == "__main__":
    unittest.main()
